import type { AppConfig } from '@/shared/types/bindings';

export const FALLBACK_CONFIG: AppConfig = {
    version: '1.0.0',
    catalog: {
        ai: [
            {
                id: 'axelate-localai',
                nameKey: 'ui.launcher.app.axelate_localai.name',
                descKey: 'ui.launcher.app.axelate_localai.desc',
                name: 'Axelate',
                desc: 'Universal hub for pro-grade images and text.',
                icon: '🌌',
                type: 'local',
                repoUrl: 'https://github.com/F0RLE/Axelate_LocalAI_module',
                expectedHash: '',
                version: '1.0.0',
            },
            {
                id: 'gpt',
                nameKey: 'ui.launcher.app.gpt.name',
                descKey: 'ui.launcher.app.gpt.desc',
                name: 'GPT',
                desc: 'Smart assistant for chat, coding and images.',
                icon: '🤖',
                type: 'api',
                repoUrl: null,
                expectedHash: null,
                version: '1.0.0',
            },
            {
                id: 'gemini',
                nameKey: 'ui.launcher.app.gemini.name',
                descKey: 'ui.launcher.app.gemini.desc',
                name: 'Gemini',
                desc: 'Massive-context analysis and creative visuals.',
                icon: '✨',
                type: 'api',
                repoUrl: null,
                expectedHash: null,
                version: '1.0.0',
            },
            {
                id: 'claude',
                nameKey: 'ui.launcher.app.claude.name',
                descKey: 'ui.launcher.app.claude.desc',
                name: 'Claude',
                desc: 'Advanced AI for analysis and creativity.',
                icon: '✱',
                type: 'api',
                repoUrl: null,
                expectedHash: null,
                version: '1.0.0',
            },
            {
                id: 'llama',
                nameKey: 'ui.launcher.app.llama.name',
                descKey: 'ui.launcher.app.llama.desc',
                name: 'Llama',
                desc: 'Powerful open models.',
                icon: '🦙',
                type: 'api',
                repoUrl: null,
                expectedHash: null,
                version: '1.0.0',
            },
            {
                id: 'deepseek',
                nameKey: 'ui.launcher.app.deepseek.name',
                descKey: 'ui.launcher.app.deepseek.desc',
                name: 'DeepSeek',
                desc: 'Specialized models for coding.',
                icon: '🧠',
                type: 'api',
                repoUrl: null,
                expectedHash: null,
                version: '1.0.0',
            },
        ],
        services: [
            {
                id: 'axelate-telegram-bot',
                nameKey: 'ui.launcher.app.axelate_telegram.name',
                descKey: 'ui.launcher.app.axelate_telegram.desc',
                name: 'Axelate Telegram Bot',
                desc: 'LLM rewriting, image gen, channel posting.',
                icon: '🤖',
                type: 'local',
                repoUrl: 'https://github.com/F0RLE/Axelate-tg-bot-module',
                expectedHash: '',
                version: '1.0.0',
            },
        ],
        stars: [],
    },
    apiProviders: [
        { id: 'gpt', name: 'GPT', providerType: 'api', baseUrl: 'https://api.openai.com/v1' },
        { id: 'gemini', name: 'Gemini', providerType: 'api' },
        { id: 'claude', name: 'Claude', providerType: 'api' },
        { id: 'llama', name: 'Llama', providerType: 'api' },
        { id: 'deepseek', name: 'DeepSeek', providerType: 'api' },
    ],
    models: {
        gpt: {
            'gpt-5.3-codex': {
                descKey: '',
                name: 'GPT‑5.3 Codex',
                desc: 'Top coding and developer workflows — best code reasoning and generation.',
                pricing: [
                    { tier: 'Input', note: '$1.75' },
                    { tier: 'Output', note: '$14.00' },
                ],
                stats: { speed: 6, logic: 10, creative: 8 },
                apiModels: null,
            },
            'gpt-5.2': {
                descKey: '',
                name: 'GPT‑5.2',
                desc: 'Balanced general reasoning, multimodal tasks and productivity AI.',
                pricing: [
                    { tier: 'Input', note: '$1.75' },
                    { tier: 'Output', note: '$14.00' },
                ],
                stats: { speed: 7, logic: 9, creative: 9 },
                apiModels: null,
            },
            'gpt-5-mini': {
                descKey: '',
                name: 'GPT‑5 Mini',
                desc: 'Fast, cost‑effective model with good all‑around skills.',
                pricing: [
                    { tier: 'Input', note: '$0.30' },
                    { tier: 'Output', note: '$1.00' },
                ],
                stats: { speed: 10, logic: 5, creative: 5 },
                apiModels: null,
            },
        },
        gemini: {
            'gemini-3-pro': {
                descKey: '',
                name: 'Gemini 3 Pro',
                desc: 'Huge context (up to ~1M), strong multimodal and reasoning skills.',
                pricing: [
                    { tier: 'Input', note: '$2.00' },
                    { tier: 'Output', note: '$12.00' },
                ],
                stats: { speed: 6, logic: 9, creative: 9 },
                apiModels: null,
            },
            'gemini-3-flash': {
                descKey: '',
                name: 'Gemini 3 Flash',
                desc: 'High‑volume, affordable model with long context and speed.',
                pricing: [
                    { tier: 'Input', note: '$0.50' },
                    { tier: 'Output', note: '$3.00' },
                ],
                stats: { speed: 9, logic: 7, creative: 7 },
                apiModels: null,
            },
        },
        claude: {
            'claude-opus-4.6': {
                descKey: '',
                name: 'Claude Opus 4.6',
                desc: 'Enterprise‑grade reasoning and long context work, adaptive thinking.',
                pricing: [
                    { tier: 'Input', note: '$5.00' },
                    { tier: 'Output', note: '$25.00' },
                ],
                stats: { speed: 5, logic: 10, creative: 10 },
                apiModels: null,
            },
            'claude-sonnet-4.5': {
                descKey: '',
                name: 'Claude Sonnet 4.5',
                desc: 'Balanced performance for general tasks and coding workflows.',
                pricing: [
                    { tier: 'Input', note: '$3.00' },
                    { tier: 'Output', note: '$15.00' },
                ],
                stats: { speed: 7, logic: 8, creative: 8 },
                apiModels: null,
            },
            'claude-haiku-4.5': {
                descKey: '',
                name: 'Claude Haiku 4.5',
                desc: 'Cost‑efficient model for high‑volume tasks.',
                pricing: [
                    { tier: 'Input', note: '$1.00' },
                    { tier: 'Output', note: '$5.00' },
                ],
                stats: { speed: 9, logic: 6, creative: 5 },
                apiModels: null,
            },
        },
        deepseek: {
            'deepseek-v3.2': {
                descKey: '',
                name: 'DeepSeek V3.2',
                desc: 'Open‑source alternative with strong reasoning at low cost.',
                pricing: [
                    { tier: 'Input', note: '$0.27' },
                    { tier: 'Output', note: '$1.10' },
                ],
                stats: { speed: 8, logic: 8, creative: 6 },
                apiModels: null,
            },
            'deepseek-chat': {
                descKey: '',
                name: 'DeepSeek Chat',
                desc: 'Budget‑friendly conversational model.',
                pricing: [
                    { tier: 'Input', note: '$0.14' },
                    { tier: 'Output', note: '$0.28' },
                ],
                stats: { speed: 9, logic: 6, creative: 5 },
                apiModels: null,
            },
        },
        llama: {
            'llama-4-scout': {
                descKey: '',
                name: 'Llama 4 Scout',
                desc: 'Open self‑hosted model with massive context scaling.',
                pricing: [
                    { tier: 'Input', note: 'Self‑hosted' },
                    { tier: 'Output', note: 'Self‑hosted' },
                ],
                stats: { speed: 7, logic: 7, creative: 7 },
                apiModels: null,
            },
            'llama-4-maverick': {
                descKey: '',
                name: 'Llama 4 Maverick',
                desc: '400B parameter general purpose powerhouse.',
                pricing: [
                    { tier: 'Input', note: 'Self‑hosted' },
                    { tier: 'Output', note: 'Self‑hosted' },
                ],
                stats: { speed: 5, logic: 9, creative: 9 },
                apiModels: null,
            },
        },
    },
};
