const fs = require('node:fs');
const path = require('node:path');

const inputName = process.argv[2];
if (!inputName) {
    console.error('Usage: node scripts/scaffold-ui.js FeatureName');
    process.exit(1);
}

// Helpers
const toKebab = (str) => str.replaceAll(/([a-z0-9])([A-Z])/g, '$1-$2').toLowerCase();
const kebabName = toKebab(inputName);
const className = inputName.charAt(0).toUpperCase() + inputName.slice(1);

const basePath = path.join(__dirname, '..', 'src', 'features', kebabName);
const stylesPath = path.join(__dirname, '..', 'src', 'styles', 'features', `${kebabName}.css`);

// Guard: Early exit if feature exists
if (fs.existsSync(basePath)) {
    console.error(`❌ Feature already exists at: ${path.relative(process.cwd(), basePath)}`);
    process.exit(1);
}

console.log(`\n🏗️  Scaffolding UI feature: ${className}...\n`);

// Standard header
const header = `/**
 * Generated by scaffold-ui.js
 * Follow CODING_STANDARDS §62 (Unified UI Architecture)
 */`;

// 1. Create directory structure
const dirs = [
    basePath,
    path.join(basePath, 'ui'),
    path.join(basePath, 'services'),
    path.join(basePath, 'types'),
];

dirs.forEach(dir => {
    if (!fs.existsSync(dir)) {
        fs.mkdirSync(dir, { recursive: true });
        console.log(`✅ Created directory: ${path.relative(process.cwd(), dir)}`);
    }
});

// 2. Create UI component
const uiTemplate = `${header}

import { BaseComponent } from '../../../shared/ui/BaseComponent';
import { logger } from '../../../shared/services/LoggerService';

/**
 * @class ${className}UI
 * @extends BaseComponent
 * @description UI controller for the ${className} feature.
 */
export class ${className}UI extends BaseComponent {
    constructor() {
        super();
    }

    /**
     * Component initialization logic.
     * Use super.getElement() for cached lookups.
     */
    protected async onInit(): Promise<void> {
        logger.debug('[${className}UI] Initializing');

        // Example: this.getElement('btn').addEventListener('click', () => {}, { 
        //    signal: this._abortController!.signal 
        // });
    }

    /**
     * Render or update the DOM.
     */
    protected render(): void {
        const root = this.getElement('${kebabName}-root');
        if (root) {
            root.innerHTML = \`<div class="${kebabName}-container">
                <h1>\${i18n?.t('${kebabName}.title') || '${className}'}</h1>
            </div>\`;
        }
    }

    /**
     * Cleanup specialized resources.
     * Listeners added with _abortController.signal are AUTO-MANAGED.
     */
    protected onDestroy(): void {
        logger.debug('[${className}UI] Destroying');
    }
}
`;

fs.writeFileSync(path.join(basePath, 'ui', `${className}UI.ts`), uiTemplate);
console.log(`✅ Created UI class: src/features/${kebabName}/ui/${className}UI.ts`);

// 3. Create index.ts
const indexTemplate = `${header}

export * from './ui/${className}UI';
`;
fs.writeFileSync(path.join(basePath, 'index.ts'), indexTemplate);
console.log(`✅ Created entry point: src/features/${kebabName}/index.ts`);

// 4. Create CSS file
const cssTemplate = `/* ${className} Feature Styles */
.${kebabName}-root {
    padding: var(--spacing-lg);
}

.${kebabName}-container {
    animation: fadeIn var(--transition-normal) ease-out;
}
`;

if (!fs.existsSync(stylesPath)) {
    fs.mkdirSync(path.dirname(stylesPath), { recursive: true });
    fs.writeFileSync(stylesPath, cssTemplate);
    console.log(`✅ Created styles: src/styles/features/${kebabName}.css`);

    // Update main.css
    const mainCssPath = path.join(__dirname, '..', 'src', 'styles', 'main.css');
    if (fs.existsSync(mainCssPath)) {
        let mainCss = fs.readFileSync(mainCssPath, 'utf8');
        const importLine = `@import './features/${kebabName}.css';`;
        if (!mainCss.includes(importLine)) {
            // Append before the end
            mainCss = mainCss.trim() + `\n${importLine}\n`;
            fs.writeFileSync(mainCssPath, mainCss);
            console.log(`✅ Updated: src/styles/main.css`);
        }
    }
}

console.log(`\n✨ Feature "${className}" scaffolded successfully! 🚀\n`);
console.log(`Next steps:`);
console.log(`1. Add translations to locales/*.json`);
console.log(`2. Inject markup in index.html (if needed)`);
console.log(`3. Instantiate and init() in AppUI.ts or relevant controller`);
