//! Axelate Backend Library
//!
//! Core backend logic for the Axelate platform.

// ============================================================
// Crate-Level Strictness Attributes
// ============================================================
#![deny(clippy::all, missing_docs, rust_2018_idioms)]
#![warn(clippy::cargo, clippy::pedantic, clippy::nursery)]
// Allow specific patterns used by Tauri/Specta macros
#![allow(
    clippy::must_use_candidate,
    clippy::missing_errors_doc,
    clippy::missing_panics_doc,
    clippy::too_many_lines,
    clippy::module_name_repetitions,
    clippy::doc_markdown, // False positives for technical terms
    clippy::struct_excessive_bools, // UI state requires multiple bool flags
    clippy::items_after_statements, // Helper closures defined where used
    clippy::option_if_let_else, // Explicit if-let often clearer than map_or
    clippy::significant_drop_tightening, // Complex lock patterns require flexibility
    clippy::unreachable, // Generated by specta/tauri macros
    clippy::if_then_some_else_none, // Complex initialization patterns
    clippy::useless_let_if_seq // Complex GPU/VRAM initialization with multiple conditions
)]

/// API Layer (Tauri Commands)
pub mod api;
/// App-level window management and system tray setup
pub mod app;
/// Domain Layer (Business Logic)
pub mod domain;
/// Error types and conversions for the application
pub mod errors;
/// Infrastructure Layer (Technical Services)
pub mod infrastructure;
/// Data structures for configuration, system state, and IPC
pub mod models;
/// Utility functions for paths, process management, and Windows APIs
pub mod utils;

#[cfg(test)]
mod tests;

// Re-export API modules to match the flat structure expected by collect_commands!
use api::{
    ai, license,
    modules::{self, downloader},
    secure,
    settings::{self, theme, translations, ui_state, window_settings},
    system::{self, bootstrap, config, health, logs},
    window,
};

// Import app-level helpers
use app::{
    IS_QUITTING,
    tray::setup_system_tray,
    window::{
        create_main_window, setup_global_shortcut, setup_webview2_cache, show_and_focus_window,
    },
};

// Import necessary services for run() and create_main_window()
use domain::ai::custom_model_service;
use domain::monitoring::system_monitor;
use infrastructure::{
    config::{
        settings::SettingsService, ui_state::UiStateService, window_settings::WindowSettingsService,
    },
    filesystem::{file_service, local_file_service::LocalFileService},
    http::server,
    logging::logger,
    persistence::json_store::JsonStore,
};

#[cfg(debug_assertions)]
use specta_typescript::Typescript;
use std::sync::atomic::Ordering;
use tauri::Manager;
use tauri_specta::{Builder, collect_commands};

/// Creates and configures the Specta builder with all application commands.
pub fn create_specta_builder() -> Builder<tauri::Wry> {
    Builder::<tauri::Wry>::new().commands(collect_commands![
        health::get_health,
        config::get_config,
        settings::get_settings,
        settings::save_settings,
        settings::save_setting,
        settings::get_system_language,
        logs::get_logs,
        logs::clear_logs,
        logs::add_log,
        logs::log_batch,
        downloader::download_module,
        downloader::check_module_installed,
        downloader::get_module_path,
        downloader::delete_module,
        downloader::list_module_files,
        downloader::set_download_settings,
        system::get_system_stats,
        system::get_gpu_info,
        system::set_monitoring_paused,
        modules::get_modules,
        modules::control_module,
        modules::get_module_status,
        modules::launch_module,
        window::minimize_window,
        window::maximize_window,
        window::close_window,
        window::show_window,
        window::hide_window,
        translations::get_translations,
        license::get_license_status,
        license::activate_license,
        license::deactivate_license,
        license::check_feature,
        theme::get_theme_colors,
        window_settings::get_window_settings,
        window_settings::save_window_size,
        window_settings::save_window_position,
        window_settings::save_maximized_state,
        window_settings::save_zoom_level,
        window_settings::set_webview_zoom,
        window_settings::get_webview_zoom,
        window_settings::get_resolution_zoom,
        window_settings::get_window_config,
        window_settings::get_window_policy,
        ui_state::get_ui_state,
        ui_state::save_ui_state,
        bootstrap::get_app_bootstrap_data,
        secure::save_secure_key,
        secure::get_secure_key,
        ai::send_chat_message,
        ai::validate_api_key,
        ai::clear_chat_history,
        ai::get_chat_history,
        ai::count_tokens,
        custom_model_service::get_custom_models,
        custom_model_service::add_custom_model,
        custom_model_service::remove_custom_model,
        file_service::process_file_content,
    ])
}

#[cfg_attr(mobile, tauri::mobile_entry_point)]
#[allow(unsafe_code)]
#[allow(clippy::large_stack_frames)]
/// Main entry point for the Tauri application
#[allow(clippy::print_stderr)]
pub fn run() {
    // 1. Mandatory Environment Validation (WebView2 & Internet)
    {
        use crate::domain::system::startup::EnvironmentValidator;
        use crate::infrastructure::system::startup::WindowsStartupInfrastructure;

        let validator = EnvironmentValidator::new(
            Box::new(WindowsStartupInfrastructure),
            Box::new(WindowsStartupInfrastructure),
            Box::new(WindowsStartupInfrastructure),
        );
        validator.validate();
    }

    // Initialize tracing
    if let Err(e) = logger::init_global_logger() {
        eprintln!("Failed to initialize logger: {e}");
    }

    tracing::debug!("Initializing Axelate...");

    setup_webview2_cache();
    let tauri_builder = tauri::Builder::default()
        .plugin(tauri_plugin_shell::init())
        .plugin(tauri_plugin_dialog::init())
        .plugin(tauri_plugin_fs::init())
        .plugin(tauri_plugin_clipboard_manager::init())
        .plugin(tauri_plugin_single_instance::init(|app, _args, _cwd| {
            if let Some(window) = app.get_webview_window("main") {
                show_and_focus_window(&window);
                #[cfg(target_os = "windows")]
                {
                    let _ = window.set_always_on_top(true);
                    std::thread::sleep(std::time::Duration::from_millis(100));
                    let _ = window.set_always_on_top(false);
                }
                system_monitor::set_paused(false);
            } else {
                create_main_window(app);
            }
            tracing::info!("Single instance lock: Second instance launch attempt detected.");
        }));

    let builder = create_specta_builder();

    #[cfg(debug_assertions)]
    builder
        .export(
            Typescript::default()
                .header("// @ts-nocheck\n/* eslint-disable */\n// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta).\n// Do not edit this file manually, as it will be overwritten.\n"),
            "../src/shared/types/bindings.ts",
        )
        .map_err(|e| log::error!("Failed to export typescript bindings: {e}"))
        .ok();

    match tauri_builder
        .invoke_handler(builder.invoke_handler())
        .setup(|app| {
            // --- Dependency Injection System ---
            let file_service: std::sync::Arc<dyn crate::domain::filesystem::service::FileService> =
                std::sync::Arc::new(LocalFileService::new());
            let json_store = JsonStore::new(std::sync::Arc::clone(&file_service));

            let settings_service = SettingsService::new(json_store.clone());
            let ui_state_service = UiStateService::new(json_store.clone());
            let window_settings_service = WindowSettingsService::new(json_store.clone());

            app.manage(file_service);
            app.manage(json_store);
            app.manage(settings_service.clone());
            app.manage(ui_state_service);
            app.manage(window_settings_service);
            app.manage(crate::domain::modules::downloader::DownloaderService::new());

            crate::utils::paths::init_filesystem().ok();

            // Start system monitoring with events
            system_monitor::start_monitoring(app.handle().clone(), 2000);

            #[cfg(desktop)]
            setup_global_shortcut(app)?;

            // Start HTTP Server
            server::start_server(app.handle().clone(), settings_service);

            setup_system_tray(app)?;
            tracing::info!("Axelate is ready");
            Ok(())
        })
        .on_window_event(|_window, event| {
            if let tauri::WindowEvent::CloseRequested { .. } = event {
                system_monitor::set_paused(true);
                crate::utils::memory::trim_memory();
            }
        })
        .build(tauri::generate_context!())
    {
        Ok(app) => app.run(|_app_handle, event| {
            if let tauri::RunEvent::ExitRequested { api, .. } = event {
                log::info!(
                    "Received RunEvent::ExitRequested. IS_QUITTING: {}",
                    IS_QUITTING.load(Ordering::Relaxed)
                );
                if IS_QUITTING.load(Ordering::Relaxed) {
                    log::info!("App Exiting...");
                } else {
                    crate::utils::memory::trim_memory();
                    api.prevent_exit();
                }
            }
        }),
        Err(e) => {
            log::error!("Error building application: {e}");
            std::process::exit(1);
        }
    }
}
