// @ts-nocheck
/* eslint-disable */
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta).
// Do not edit this file manually, as it will be overwritten.

// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
/**
 * Checks backend health status
 */
async getHealth() : Promise<Result<string, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_health") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Loads application configuration with module installation status
 */
async getConfig() : Promise<Result<AppConfig, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_config") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Retrieves application settings (theme, language, GPU, debug)
 */
async getSettings() : Promise<Result<AppSettings, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_settings") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Saves application settings
 */
async saveSettings(settings: AppSettings) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_settings", { settings }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Saves a single setting by key-value pair
 */
async saveSetting(key: string, value: string) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_setting", { key, value }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Detects and returns the current system language code
 */
async getSystemLanguage() : Promise<Result<string, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_system_language") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Retrieves log entries since a given timestamp
 */
async getLogs(since: number) : Promise<Result<LogEntry[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_logs", { since }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Clears all stored log entries
 */
async clearLogs() : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("clear_logs") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Adds a single log entry to the log store
 */
async addLog(msg: string, source: string, level: string) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_log", { msg, source, level }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Adds multiple log entries in batch from frontend
 */
async logBatch(logs: BatchLogEntry[]) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("log_batch", { logs }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Downloads and verifies a module from a Git repository
 */
async downloadModule(moduleId: string, repoUrl: string, expectedHash: string | null, dlType: string | null) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("download_module", { moduleId, repoUrl, expectedHash, dlType }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Checks if a module is already installed locally
 */
async checkModuleInstalled(moduleId: string) : Promise<Result<boolean, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("check_module_installed", { moduleId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Retrieves the filesystem path to a module's directory
 */
async getModulePath(moduleId: string) : Promise<Result<string, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_module_path", { moduleId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Deletes a module from local storage
 */
async deleteModule(moduleId: string) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_module", { moduleId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Lists all files in a module's directory
 */
async listModuleFiles(moduleId: string) : Promise<Result<string[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_module_files", { moduleId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Configures download bandwidth limits
 */
async setDownloadSettings(enabled: boolean, maxSpeed: number) : Promise<void> {
    await TAURI_INVOKE("set_download_settings", { enabled, maxSpeed });
},
/**
 * Cancels an in-progress module download
 */
async cancelDownload(moduleId: string) : Promise<boolean> {
    return await TAURI_INVOKE("cancel_download", { moduleId });
},
/**
 * Retrieves real-time system statistics (CPU, RAM, GPU, disk, network)
 */
async getSystemStats() : Promise<Result<SystemStats, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_system_stats") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Retrieves GPU model name or indicates if no GPU is present
 */
async getGpuInfo() : Promise<Result<string, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_gpu_info") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Pauses or resumes system monitoring
 */
async setMonitoringPaused(paused: boolean) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_monitoring_paused", { paused }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Retrieves list of all available modules (AI and services)
 */
async getModules() : Promise<Result<Module[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_modules") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Controls a module (start, stop, restart)
 */
async controlModule(request: ControlRequest) : Promise<Result<ControlResponse, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("control_module", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Retrieves runtime status of a specific module
 */
async getModuleStatus(moduleId: string) : Promise<Result<string, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_module_status", { moduleId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Launches a module (local or API-based)
 */
async launchModule(moduleId: string) : Promise<Result<LaunchResponse, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("launch_module", { moduleId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Minimizes the application window
 */
async minimizeWindow() : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("minimize_window") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Maximizes or unmaximizes the window
 */
async maximizeWindow() : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("maximize_window") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Closes the window gracefully (app remains in tray)
 */
async closeWindow() : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("close_window") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Shows and focuses the window
 */
async showWindow() : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("show_window") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Hides the window
 */
async hideWindow() : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("hide_window") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Retrieves translation strings for the specified language
 */
async getTranslations(lang: string) : Promise<Result<JsonValue, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_translations", { lang }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Retrieves current license activation status
 */
async getLicenseStatus() : Promise<Result<LicenseStatusResponse, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_license_status") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Activates a license key with optional email
 */
async activateLicense(key: string, email: string | null) : Promise<Result<LicenseStatus, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("activate_license", { key, email }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Deactivates the current license
 */
async deactivateLicense() : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("deactivate_license") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Checks if a specific feature is enabled by the current license
 */
async checkFeature(feature: string) : Promise<Result<boolean, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("check_feature", { feature }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Retrieves current theme color palette
 */
async getThemeColors() : Promise<Result<{ [key in string]: string }, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_theme_colors") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Retrieves persisted window settings (size, position, maximized state)
 */
async getWindowSettings() : Promise<Result<WindowSettings, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_window_settings") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Saves window dimensions to disk
 */
async saveWindowSize(width: number, height: number) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_window_size", { width, height }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Saves window screen position to disk
 */
async saveWindowPosition(x: number, y: number) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_window_position", { x, y }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Saves maximized/unmaximized state to disk
 */
async saveMaximizedState(maximized: boolean) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_maximized_state", { maximized }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Saves global zoom level to UI state
 */
async saveZoomLevel(zoom: number) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_zoom_level", { zoom }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Set `WebView` zoom level and persist for current resolution.
 * This is the ONLY place that saves zoom — always saves both global and per-resolution.
 */
async setWebviewZoom(zoom: number) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_webview_zoom", { zoom }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Retrieves current global `WebView` zoom level
 */
async getWebviewZoom() : Promise<Result<number, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_webview_zoom") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get the effective zoom for the current monitor resolution.
 * Read-only — never auto-saves, so "user set" is always distinguishable from "defaulted".
 */
async getResolutionZoom() : Promise<Result<number, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_resolution_zoom") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Retrieves window configuration settings
 */
async getWindowConfig() : Promise<WindowConfig> {
    return await TAURI_INVOKE("get_window_config");
},
/**
 * Calculates window layout policy based on screen size and zoom
 */
async getWindowPolicy() : Promise<Result<WindowPolicy, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_window_policy") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Retrieves persisted UI state (sidebar, zoom, selected modules)
 */
async getUiState() : Promise<Result<UIState, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_ui_state") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Saves UI state to persistent storage
 */
async saveUiState(state: UIState) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_ui_state", { state }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Retrieves all application state and configuration during app startup
 */
async getAppBootstrapData() : Promise<Result<BootstrapData, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_app_bootstrap_data") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Saves anAPI key securely to system credential storage
 */
async saveSecureKey(service: string, key: string) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_secure_key", { service, key }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Retrieves an API key from system credential storage
 */
async getSecureKey(service: string) : Promise<Result<string | null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_secure_key", { service }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Checks whether a non-empty API key exists in secure storage
 */
async hasSecureKey(service: string) : Promise<Result<boolean, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("has_secure_key", { service }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Returns non-sensitive metadata for a stored key without exposing the secret.
 */
async getSecureKeyMeta(service: string) : Promise<Result<SecureKeyMeta, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_secure_key_meta", { service }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Sends a chat message to the AI provider and streams the response
 */
async sendChatMessage(request: ChatRequest) : Promise<Result<ChatResponse, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("send_chat_message", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Validates an API key for the specified provider
 */
async validateApiKey(provider: string, key: string) : Promise<Result<boolean, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("validate_api_key", { provider, key }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Validates the stored OpenRouter API key without exposing it to the frontend
 */
async validateStoredApiKey(provider: string) : Promise<Result<boolean, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("validate_stored_api_key", { provider }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Clears chat history for a specific session
 */
async clearChatHistory(sessionId: string) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("clear_chat_history", { sessionId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Retrieves chat history for a specific session
 */
async getChatHistory(sessionId: string) : Promise<Result<ChatMessage[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_chat_history", { sessionId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Removes the latest user turn and any following assistant replies from a session.
 */
async rewindLastTurn(sessionId: string) : Promise<Result<string | null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("rewind_last_turn", { sessionId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Counts tokens in text for the specified model
 */
async countTokens(text: string, model: string | null) : Promise<Result<number, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("count_tokens", { text, model }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Sends an image generation request to the connected AI provider
 */
async generateImage(request: ImageGenerationRequest) : Promise<Result<ImageGenerationResponse, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("generate_image", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Starts image generation as a detached backend task and restores the window on completion.
 */
async generateImageBackground(request: ImageGenerationRequest) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("generate_image_background", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Deletes a previously saved chat image from disk.
 */
async deleteChatImage(filePath: string) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_chat_image", { filePath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Opens the saved chat image folder in the system file manager.
 */
async openChatImageLocation(filePath: string, folderPath: string) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_chat_image_location", { filePath, folderPath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Saves a chat image to the default Pictures/axelate directory and returns the final path.
 */
async saveChatImageDefault(base64Data: string, mimeType: string) : Promise<Result<SavedChatImage, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_chat_image_default", { base64Data, mimeType }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Retrieves all custom AI models configured by the user
 */
async getCustomModels() : Promise<Result<CustomModel[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_custom_models") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Adds a new custom AI model configuration
 */
async addCustomModel(providerId: string, id: string, name: string, baseModelId: string) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_custom_model", { providerId, id, name, baseModelId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Removes a custom AI model by ID
 */
async removeCustomModel(id: string) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("remove_custom_model", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Processes file content for AI context (extracts text from files and archives)
 */
async processFileContent(name: string, data: number[]) : Promise<Result<ProcessedFile, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("process_file_content", { name, data }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Starts a local engine. Hot-swaps if another engine is active.
 */
async startEngine(config: EngineConfig) : Promise<Result<EngineStatus, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("start_engine", { config }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Stops all running engines.
 */
async stopEngine() : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("stop_engine") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Stops the engine in a specific capability slot (text, image, vision).
 */
async stopEngineSlot(capability: Capability) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("stop_engine_slot", { capability }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Gets the current engine state (idle, starting, ready, error).
 */
async getEngineState() : Promise<Result<EngineState, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_engine_state") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Checks if an engine binary is present (in MODULES_DIR or system PATH).
 */
async checkEngineInstalled(engineId: string, binaryName: string | null) : Promise<boolean> {
    return await TAURI_INVOKE("check_engine_installed", { engineId, binaryName });
},
/**
 * Returns all registered engine definitions with real-time installation status.
 */
async getEngineDefinitions() : Promise<Result<EngineDefinition[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_engine_definitions") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Returns the persisted user config for an engine, or defaults if none saved yet.
 */
async getEngineConfig(engineId: string) : Promise<Result<EngineConfig, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_engine_config", { engineId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Persists user engine config (port, gpu_layers, context_size, model_path, extra_args).
 */
async setEngineConfig(config: EngineConfig) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_engine_config", { config }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

/**
 * Complete AI model definition
 */
export type AiModel = { 
/**
 * Model ID (moved from dict key)
 */
id: string; 
/**
 * Localization key for description
 */
descKey?: string; 
/**
 * Display name
 */
name: string; 
/**
 * Human-readable description
 */
desc: string; 
/**
 * Tier classification (Weak < Medium < Strong)
 */
tier: ModelTier; 
/**
 * Model size classification (optional)
 */
modelSize: string | null; 
/**
 * Release date string (YYYY-MM)
 */
releaseDate: string | null; 
/**
 * Context window size in tokens
 */
contextWindow: number | null; 
/**
 * Maximum output tokens allowed
 */
maxOutputTokens: number | null; 
/**
 * Whether the model is deprecated
 */
deprecated: boolean | null; 
/**
 * Pricing configuration (New Object Format)
 */
pricing: PricingConfig | null; 
/**
 * Performance statistics
 */
stats: ModelStats; 
/**
 * Capabilities
 */
capabilities: ModelCapabilities | null; 
/**
 * API model identifiers (mapped to `apiModels` in JSON)
 */
apiModels: ApiModelConfig | null }
/**
 * API model identifiers for different capabilities
 */
export type ApiModelConfig = { 
/**
 * Model ID for text generation
 */
text: string | null; 
/**
 * Model ID for image generation
 */
image: string | null }
/**
 * Configuration for an AI API provider (OpenAI, Gemini, Claude, etc.)
 */
export type ApiProvider = { 
/**
 * Unique identifier (e.g., "gpt", "gemini")
 */
id: string; 
/**
 * Display name (e.g., "GPT", "Gemini")
 */
name: string; 
/**
 * Localization key for description
 */
descKey?: string | null; 
/**
 * Direct description text
 */
description?: string | null; 
/**
 * Icon/emoji for UI display
 */
icon?: string | null; 
/**
 * Provider type
 */
type: ProviderType | null; 
/**
 * Base URL for API endpoints
 */
baseUrl?: string | null; 
/**
 * Environment variable name for API key
 */
apiKeyEnv?: string | null; 
/**
 * Available models configuration
 */
models?: AiModel[] | null; 
/**
 * Model aliases (UI name → API ID mappings)
 */
modelAliases?: { [key in string]: string } | null }
/**
 * Orchestrated application configuration
 */
export type AppConfig = { 
/**
 * Configuration version
 */
version: string; 
/**
 * Available AI providers (loaded from api_providers.json)
 */
apiProviders: ApiProvider[]; 
/**
 * Catalog of available apps/services (local + cloud virtual modules)
 */
catalog: ConfigCatalog }
/**
 * Application-level errors
 */
export type AppError = 
/**
 * Validation error (invalid input, malformed data)
 */
{ type: "Validation"; payload: string } | 
/**
 * Resource not found error
 */
{ type: "NotFound"; payload: string } | 
/**
 * Permission denied or unauthorized access
 */
{ type: "PermissionDenied"; payload: string } | 
/**
 * File system I/O error
 */
{ type: "Io"; payload: string } | 
/**
 * JSON serialization/deserialization error
 */
{ type: "Serialization"; payload: string } | 
/**
 * Configuration loading or parsing error
 */
{ type: "Config"; payload: string } | 
/**
 * External service or API error
 */
{ type: "External"; payload: { 
/**
 * Unique request identifier for tracing
 */
request_id: string | null; 
/**
 * error message
 */
message: string } } | 
/**
 * Internal server error (unexpected failures)
 */
{ type: "Internal"; payload: { 
/**
 * Unique request identifier for tracing
 */
request_id: string | null; 
/**
 * error message
 */
message: string } }
/**
 * Global application settings
 */
export type AppSettings = 
/**
 * Dynamic extra settings (module-specific, etc.)
 */
({ [key in string]: string }) & { 
/**
 * UI theme ("dark" or "light")
 */
theme: string; 
/**
 * Interface language code (e.g., "en", "ru", "zh")
 */
language: string; 
/**
 * Enable GPU acceleration for monitoring
 */
use_gpu: boolean; 
/**
 * Enable debug mode and logging
 */
debug_mode: boolean }
/**
 * Batch log entry from frontend
 */
export type BatchLogEntry = { 
/**
 * Log level ("info", "warn", "error")
 */
level: string; 
/**
 * Log message content
 */
message: string }
/**
 * Application bootstrap data sent to frontend during initialization
 */
export type BootstrapData = { 
/**
 * Persisted UI state
 */
uiState: UIState; 
/**
 * Window configuration settings
 */
windowConfig: WindowConfig; 
/**
 * Detected system language
 */
systemLanguage: string; 
/**
 * All available modules
 */
modules: Module[]; 
/**
 * Effective zoom for the current monitor resolution
 */
initialZoom: number }
/**
 * Breakpoints configuration.
 */
export type Breakpoints = { 
/**
 * Width for compact layout.
 */
compact: number; 
/**
 * Width for medium layout.
 */
medium: number; 
/**
 * Width for large layout.
 */
large: number }
/**
 * What an engine can do
 */
export type Capability = 
/**
 * Text generation (LLM)
 */
"text" | 
/**
 * Image generation (diffusion)
 */
"image" | 
/**
 * Image understanding (multimodal LLM)
 */
"vision"
/**
 * AI chat message with role and content
 */
export type ChatMessage = { 
/**
 * Unique message identifier (UUID v4)
 */
id?: string; 
/**
 * Role ("user", "assistant", "system")
 */
role: string; 
/**
 * Message content (text or structured data)
 */
content: JsonValue; 
/**
 * Optional signature for extended thinking
 */
thought_signature: string | null }
/**
 * AI reply content
 */
export type ChatReply = { 
/**
 * Reply text
 */
text: string; 
/**
 * Role (typically "assistant")
 */
role: string }
/**
 * AI chat request parameters
 */
export type ChatRequest = { 
/**
 * AI provider ("openai", "gemini", "local") - largely ignored now as we route via OpenRouter
 */
provider: string; 
/**
 * Model identifier
 */
model: string; 
/**
 * Chat history and new message
 */
messages: ChatMessage[]; 
/**
 * Optional API key
 */
api_key: string | null; 
/**
 * Thinking level ("low", "medium", "high")
 */
thinking_level: string | null; 
/**
 * Optional max output tokens
 */
max_tokens: number | null; 
/**
 * Session identifier for history tracking
 */
session_id: string | null }
/**
 * AI chat response
 */
export type ChatResponse = { 
/**
 * Corresponding request identifier
 */
id?: string; 
/**
 * Whether request was successful
 */
ok: boolean; 
/**
 * AI reply content
 */
reply: ChatReply | null; 
/**
 * Error message if failed
 */
error: string | null; 
/**
 * Model used
 */
model: string | null; 
/**
 * Thinking signature
 */
thought_signature: string | null; 
/**
 * Token usage metrics
 */
usage: TokenUsage | null }
/**
 * Application catalog containing available modules and services
 */
export type ConfigCatalog = { 
/**
 * AI generation modules (text, images, `LocalAI`)
 */
ai: ModuleItem[]; 
/**
 * Service integrations (Telegram, Discord)
 */
services: ModuleItem[]; 
/**
 * Starred/Favorite module IDs
 */
stars: string[] }
/**
 * Configuration field schema for module settings
 */
export type ConfigField = { 
/**
 * Field type ("text", "password", "select", "checkbox")
 */
fieldType: string; 
/**
 * Display label in UI
 */
label: string; 
/**
 * Default value
 */
default: JsonValue | null; 
/**
 * Whether field is required
 */
required: boolean; 
/**
 * Available options for "select" type
 */
options: string[] | null }
/**
 * Module control request from frontend
 */
export type ControlRequest = { 
/**
 * Module identifier (optional for global actions)
 */
module_id: string | null; 
/**
 * Control action ("start", "stop", "restart")
 */
action: string }
/**
 * Module control response to frontend
 */
export type ControlResponse = { 
/**
 * Whether the operation succeeded
 */
success: boolean; 
/**
 * Human-readable result message
 */
message: string; 
/**
 * Current module status after operation
 */
status: string | null }
/**
 * CPU (Central Processing Unit) statistics
 */
export type CpuStats = { 
/**
 * CPU usage percentage (0-100)
 */
percent: number; 
/**
 * Number of logical cores
 */
cores: number; 
/**
 * CPU model name
 */
name: string }
/**
 * User-created fine-tuned or custom AI model
 */
export type CustomModel = { 
/**
 * Unique identifier
 */
id: string; 
/**
 * Display name
 */
name: string; 
/**
 * Provider ID (e.g., "gpt", "deepseek")
 */
provider_id: string; 
/**
 * Base model identifier (e.g., "ft:gpt-3.5-turbo:...")
 */
base_model_id: string; 
/**
 * Creation timestamp (Unix epoch)
 */
created_at: number }
/**
 * Disk I/O (Input/Output) statistics
 */
export type DiskStats = { 
/**
 * Read speed (bytes/sec)
 */
readRate: number; 
/**
 * Write speed (bytes/sec)
 */
writeRate: number; 
/**
 * Disk utilization percentage (0-100)
 */
utilization: number; 
/**
 * Total disk capacity (GB)
 */
totalGb: number; 
/**
 * Disk space currently used (GB)
 */
usedGb: number; 
/**
 * Disk activity percentage (0-100)
 */
activityPercent: number }
/**
 * Runtime configuration for starting an engine
 */
export type EngineConfig = { 
/**
 * Engine identifier (matches EngineDefinition.id)
 */
engine_id: string; 
/**
 * Port to bind (local engines)
 */
port?: number; 
/**
 * Number of GPU layers (-1 = all)
 */
gpu_layers?: number; 
/**
 * Context window size
 */
context_size?: number; 
/**
 * Path to model file
 */
model_path: string | null; 
/**
 * Extra CLI arguments
 */
extra_args?: string[] }
/**
 * Static engine definition (from local_modules.json)
 */
export type EngineDefinition = { 
/**
 * Unique identifier (e.g. "llamacpp")
 */
id: string; 
/**
 * Display name
 */
name: string; 
/**
 * Description
 */
desc?: string; 
/**
 * Icon emoji
 */
icon?: string; 
/**
 * What this engine can do
 */
capabilities?: Capability[]; 
/**
 * Binary name for local engines
 */
binary?: string | null; 
/**
 * GitHub repository URL (for releases/downloads)
 */
repo_url?: string | null; 
/**
 * Current version
 */
version?: string; 
/**
 * Default port (extracted from configSchema.port.default)
 */
default_port?: number; 
/**
 * Default GPU layers (-1 = all, extracted from configSchema.gpuLayers.default)
 */
default_gpu_layers?: number; 
/**
 * Default context window size (extracted from configSchema.contextSize.default)
 */
default_context_size?: number; 
/**
 * Raw configuration schema for UI rendering (kept for frontend)
 */
config_schema?: JsonValue | null; 
/**
 * Whether the engine binary is currently installed (populated at runtime, not from JSON)
 */
installed?: boolean }
/**
 * Engine lifecycle state (for frontend)
 */
export type EngineState = 
/**
 * No engine loaded
 */
"idle" | 
/**
 * Engine is starting up
 */
{ starting: { 
/**
 * ID of the engine being started
 */
engine_id: string } } | 
/**
 * Swapping from one engine to another within a slot
 */
{ swapping: { 
/**
 * ID of the engine being stopped
 */
from: string; 
/**
 * ID of the engine being started
 */
to: string } } | 
/**
 * One or more engines are running
 */
{ ready: { 
/**
 * Active slots (one per capability)
 */
slots: SlotStatus[] } } | 
/**
 * Engine encountered an error
 */
{ error: { 
/**
 * ID of the failed engine
 */
engine_id: string; 
/**
 * Error description
 */
message: string } }
/**
 * Currently running engine
 */
export type EngineStatus = { 
/**
 * Engine identifier
 */
id: string; 
/**
 * Display name
 */
name: string; 
/**
 * Capabilities
 */
capabilities: Capability[]; 
/**
 * HTTP endpoint (e.g. "http://localhost:8081")
 */
endpoint: string; 
/**
 * Is the engine healthy and ready
 */
healthy: boolean }
/**
 * GPU (Graphics Processing Unit) statistics
 */
export type GpuStats = { 
/**
 * GPU usage percentage (0-100)
 */
usage: number; 
/**
 * Memory currently used (bytes)
 */
memoryUsed: number; 
/**
 * Total available memory (bytes)
 */
memoryTotal: number; 
/**
 * GPU temperature (Celsius)
 */
temp: number; 
/**
 * GPU model name
 */
name: string }
/**
 * Image generation request parameters
 */
export type ImageGenerationRequest = { 
/**
 * AI provider or local engine ID
 */
provider: string; 
/**
 * The text prompt for generation
 */
prompt: string; 
/**
 * Original user text before UI prompt prefixes
 */
original_prompt: string | null; 
/**
 * Model identifier
 */
model: string; 
/**
 * Optional settings namespace key when UI-selected module differs from provider id
 */
settings_key: string | null; 
/**
 * Session identifier for history tracking
 */
session_id: string | null; 
/**
 * Number of inference steps
 */
steps: number | null; 
/**
 * Guidance scale (CFG)
 */
cfg_scale: number | null; 
/**
 * Image width in pixels
 */
width: number | null; 
/**
 * Image height in pixels
 */
height: number | null; 
/**
 * Sampler algorithm
 */
sampler: string | null; 
/**
 * Random seed
 */
seed: number | null; 
/**
 * Clip skip
 */
clip_skip: number | null; 
/**
 * Optional negative prompt
 */
negative_prompt: string | null; 
/**
 * Number of images to generate (batch size)
 */
batch_size: number | null; 
/**
 * Scheduler algorithm
 */
scheduler: string | null }
/**
 * Image generation response
 */
export type ImageGenerationResponse = { 
/**
 * Base64 encoded images or URLs
 */
images: string[]; 
/**
 * Whether request was successful
 */
ok: boolean; 
/**
 * Error message if failed
 */
error: string | null }
export type JsonValue = null | boolean | number | string | JsonValue[] | { [key in string]: JsonValue }
/**
 * Module launch response indicating how to handle the module
 */
export type LaunchResponse = { 
/**
 * Action type ("`start_local`" or "navigate")
 */
action: string; 
/**
 * Page to navigate to
 */
page: string | null; 
/**
 * Provider identifier
 */
provider: string | null; 
/**
 * Optional status message
 */
message: string | null }
/**
 * License tier status
 */
export type LicenseStatus = 
/**
 * Free tier
 */
"Free" | 
/**
 * Pro tier
 */
"Pro" | 
/**
 * Enterprise tier
 */
"Enterprise" | 
/**
 * Expired license
 */
"Expired" | 
/**
 * Invalid license key
 */
"Invalid"
/**
 * License activation status response
 */
export type LicenseStatusResponse = { 
/**
 * Current license activation status
 */
status: LicenseStatus; 
/**
 * Email address associated with the license
 */
email: string | null }
/**
 * Log entry for frontend display
 */
export type LogEntry = { 
/**
 * Unix timestamp
 */
timestamp: number; 
/**
 * Log source component
 */
source: string; 
/**
 * Log level ("info", "warn", "error")
 */
level: string; 
/**
 * Log message
 */
message: string }
/**
 * Model capability flags (JSON Compatible)
 */
export type ModelCapabilities = { 
/**
 * Supports reasoning/thinking steps
 */
reasoning?: boolean; 
/**
 * Supports image input/vision
 */
vision?: boolean; 
/**
 * Supports multimodal input (audio/video)
 */
multimodal?: boolean; 
/**
 * Supports large context windows (>128k)
 */
longContext?: boolean; 
/**
 * Supports token streaming
 */
streaming?: boolean; 
/**
 * Supports function/tool calling
 */
functionCalling?: boolean }
/**
 * Performance characteristics of an AI model (0-10 scale)
 */
export type ModelStats = { 
/**
 * Response speed rating
 */
speed: number; 
/**
 * Logical reasoning capability
 */
logic: number; 
/**
 * Creative output quality
 */
creative: number }
/**
 * Tier classification for AI models
 */
export type ModelTier = 
/**
 * Entry-level or fast models
 */
"weak" | 
/**
 * Balanced models
 */
"medium" | 
/**
 * Flagship or reasoning-heavy models
 */
"strong"
/**
 * Complete module metadata and state
 */
export type Module = { 
/**
 * Unique module identifier
 */
id: string; 
/**
 * Display name
 */
name: string; 
/**
 * User-facing description
 */
description: string; 
/**
 * Semantic version (e.g., "1.0.0")
 */
version: string; 
/**
 * Author username or organization
 */
author: string; 
/**
 * Category ("ai" or "service")
 */
category: string; 
/**
 * Icon/emoji for UI display
 */
icon: string; 
/**
 * Absolute filesystem path to module directory
 */
path: string; 
/**
 * Whether module files are present locally
 */
installed: boolean; 
/**
 * Whether module is user-installed (vs. built-in)
 */
local: boolean; 
/**
 * Whether module is enabled for auto-start
 */
enabled: boolean; 
/**
 * Current runtime status ("running", "stopped", "error")
 */
status: string | null; 
/**
 * Whether module can be deleted by user
 */
isDeletable: boolean; 
/**
 * Current configuration values
 */
config: { [key in string]: JsonValue }; 
/**
 * Configuration schema definition
 */
configSchema: { [key in string]: ConfigField } | null }
/**
 * Catalog item for downloadable modules
 */
export type ModuleItem = { 
/**
 * Unique module identifier
 */
id: string; 
/**
 * Localization key for name
 */
nameKey: string; 
/**
 * Localization key for description
 */
descKey: string; 
/**
 * Display name
 */
name: string; 
/**
 * Description text
 */
desc: string; 
/**
 * Icon/emoji
 */
icon: string; 
/**
 * Module type ("api" or "service")
 */
type: string; 
/**
 * Download type ("source" or "release")
 */
dlType?: string | null; 
/**
 * Engine capabilities (e.g. `["text"]`, `["image"]`)
 */
capabilities?: string[]; 
/**
 * Binary executable name for local engines (e.g. "llama-server")
 */
binary?: string | null; 
/**
 * GitHub repository URL
 */
repoUrl: string | null; 
/**
 * SHA-256 hash for integrity verification
 */
expectedHash: string | null; 
/**
 * Semantic version (e.g., "1.0.0")
 */
version?: string; 
/**
 * Raw configSchema from JSON (used by engine registry to extract typed defaults)
 */
configSchema?: JsonValue | null }
/**
 * Network I/O statistics
 */
export type NetworkStats = { 
/**
 * Download speed (bytes/sec)
 */
downloadRate: number; 
/**
 * Upload speed (bytes/sec)
 */
uploadRate: number; 
/**
 * Total bytes received since boot
 */
totalReceived: number; 
/**
 * Total bytes sent since boot
 */
totalSent: number; 
/**
 * Network utilization percentage (0-100)
 */
utilization: number; 
/**
 * Network activity percentage (0-100)
 */
activityPercent: number }
/**
 * Pricing configuration for a model
 */
export type PricingConfig = { 
/**
 * Cost per 1M input tokens
 */
input_per_1m: number | null; 
/**
 * Cost per 1M output tokens
 */
output_per_1m: number | null; 
/**
 * Currency code
 */
currency: string | null; 
/**
 * Additional notes
 */
notes: string | null }
/**
 * Processed file content result
 */
export type ProcessedFile = { 
/**
 * File name
 */
name: string; 
/**
 * Extracted text content
 */
content: string; 
/**
 * Whether file was a ZIP archive
 */
is_archive: boolean; 
/**
 * Processing error if any
 */
error: string | null }
/**
 * Type of AI provider
 */
export type ProviderType = 
/**
 * Standard OpenAI API
 */
"openai" | 
/**
 * Google Gemini API
 */
"google" | 
/**
 * Anthropic Claude API (via OpenRouter or direct)
 */
"anthropic" | 
/**
 * OpenAI-compatible local or cloud API
 */
"openai-compatible" | 
/**
 * Generic API provider
 */
"api" | 
/**
 * Local module inference
 */
"local"
/**
 * RAM (Random Access Memory) statistics
 */
export type RamStats = { 
/**
 * RAM usage percentage (0-100)
 */
percent: number; 
/**
 * RAM currently used (GB)
 */
usedGb: number; 
/**
 * Total RAM capacity (GB)
 */
totalGb: number; 
/**
 * RAM available for allocation (GB)
 */
availableGb: number }
/**
 * Result of saving a generated chat image to disk.
 */
export type SavedChatImage = { 
/**
 * Absolute path to the saved image file.
 */
file_path: string; 
/**
 * Absolute path to the folder containing the saved image.
 */
folder_path: string }
/**
 * Non-sensitive metadata for a securely stored key.
 */
export type SecureKeyMeta = { 
/**
 * Whether a non-empty key exists for the requested service.
 */
exists: boolean; 
/**
 * Character length of the stored key, if present.
 */
length: number }
/**
 * Currently selected module in UI
 */
export type SelectedModule = { 
/**
 * Module identifier
 */
id: string; 
/**
 * Display name
 */
name: string; 
/**
 * Localization key for name
 */
nameKey: string | null; 
/**
 * Icon/emoji
 */
icon: string; 
/**
 * Module type
 */
type: string; 
/**
 * Localization key for description
 */
descKey: string | null; 
/**
 * Description text
 */
desc: string }
/**
 * Status of a single capability slot
 */
export type SlotStatus = { 
/**
 * Which capability this slot serves
 */
capability: Capability; 
/**
 * Engine running in this slot
 */
engine: EngineStatus }
/**
 * Complete system statistics snapshot
 */
export type SystemStats = { 
/**
 * CPU usage and information
 */
cpu: CpuStats; 
/**
 * RAM usage and availability
 */
ram: RamStats; 
/**
 * GPU usage (if available)
 */
gpu: GpuStats | null; 
/**
 * VRAM usage (if GPU present)
 */
vram: VramStats | null; 
/**
 * Disk I/O statistics
 */
disk: DiskStats; 
/**
 * Network I/O statistics
 */
network: NetworkStats; 
/**
 * Current process ID
 */
pid: number; 
/**
 * CPU usage of the current process (0-100)
 */
appCpu: number; 
/**
 * Memory used by the current process (bytes)
 */
appMemory: number }
/**
 * Thresholds configuration.
 */
export type Thresholds = { 
/**
 * Warning threshold width.
 */
warningWidth: number; 
/**
 * Warning threshold height.
 */
warningHeight: number; 
/**
 * Small screen threshold width.
 */
smallScreenWidth: number; 
/**
 * Small screen threshold height.
 */
smallScreenHeight: number }
/**
 * Token usage statistics
 */
export type TokenUsage = { 
/**
 * Tokens in the prompt
 */
prompt_tokens: number; 
/**
 * Tokens in the completion
 */
completion_tokens: number; 
/**
 * Total tokens used
 */
total_tokens: number }
/**
 * UI State that persists across sessions
 */
export type UIState = { 
/**
 * Sidebar collapsed state
 */
sidebar_collapsed: boolean; 
/**
 * Sidebar width in pixels
 */
sidebar_width: number; 
/**
 * Hidden navigation items (page IDs)
 */
hidden_nav_items: string[]; 
/**
 * Hidden system monitor items
 */
hidden_monitors: string[]; 
/**
 * Card widths map (`card_id` -> "full" | "half")
 */
card_widths: { [key in string]: string }; 
/**
 * Download settings
 */
download_limit_enabled: boolean; 
/**
 * Maximum download speed in MB/s
 */
download_max_speed: number; 
/**
 * Selected modules by category
 */
selected_modules: { [key in string]: SelectedModule }; 
/**
 * Global Zoom Level
 */
zoom_level: number; 
/**
 * Selected AI Models (`AppID` -> `ModelKey`)
 */
selected_ai_models: { [key in string]: string }; 
/**
 * Last visited page ID
 */
last_page: string | null; 
/**
 * Per-resolution zoom levels ("WxH" -> value)
 * Per-resolution zoom levels (e.g., "1920x1080" -> 1.2)
 */
resolution_zoom: { [key in string]: number }; 
/**
 * Sound effects enabled state
 */
sound_enabled: boolean; 
/**
 * Selected reasoning level by AI provider
 */
ai_thinking_level?: { [key in string]: string }; 
/**
 * Last provider activated in the UI
 */
last_active_provider?: string | null; 
/**
 * Current persistent AI session identifier
 */
ai_session_id?: string | null; 
/**
 * Preferred launcher interface language
 */
preferred_language?: string | null; 
/**
 * Request to reopen the chat and reveal the latest message after background work.
 */
pending_chat_reveal?: boolean }
/**
 * VRAM (Video RAM) statistics
 */
export type VramStats = { 
/**
 * VRAM usage percentage (0-100)
 */
percent: number; 
/**
 * VRAM currently used (GB)
 */
usedGb: number; 
/**
 * Total VRAM capacity (GB)
 */
totalGb: number }
/**
 * Overall window configuration combining breakpoints and thresholds.
 */
export type WindowConfig = { 
/**
 * Breakpoint settings.
 */
breakpoints: Breakpoints; 
/**
 * Threshold settings.
 */
thresholds: Thresholds }
/**
 * Layout policy based on screen size and current window dimensions.
 */
export type WindowPolicy = { 
/**
 * True if the screen is considered "small" (mobile/tablet/small laptop).
 */
isSmallScreen: boolean; 
/**
 * True if a layout warning should be shown.
 */
showWarning: boolean }
/**
 * Persistent window state.
 */
export type WindowSettings = { 
/**
 * Window width.
 */
width: number; 
/**
 * Window height.
 */
height: number; 
/**
 * Horizontal screen position.
 */
x: number | null; 
/**
 * Vertical screen position.
 */
y: number | null; 
/**
 * True if the window is maximized.
 */
maximized: boolean }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
